### ISSUE TITLE
This vs. grunt-contrib-compass

### ISSUE THREAD

**Issue by ghost** [khalillechelt/grunt-compass#31]
Just a short question: when grunt 0.4 is released, will this be maintained in the future or should I have a look at grunt-contrib-compass instead?

**Comment by khalillechelt** [comment]
I will keep maintaining this since it is still more flexible than the contrib version.

**Comment by ghost** [comment]
Good to know. Thanks a lot for keeping it up!

**Comment by khalillechelt** [comment]
Happy to :smiley:

**Comment by MoOx** [comment]
Why is it more flexible ? I've issue with grunt-contrib-compass because it require a config.rb (otherwise 

```
Running "compass:dist" (compass) task
Nothing to compile. If you're trying to start a new project, you have left off the directory argument.
Run "compass -h" to get help.
```

). Does this plugin require `compass create` command (=> config.rb ?) ?

**Comment by khalillechelt** [comment]
No it does not require a config.rb but you can configure it to use one if you want to.

**Comment by MoOx** [comment]
_Forgot what I said. I does not use grunt-contrib-compass correctly._

So you didn't answer to "Why is it more flexible ?" :p

**Comment by khalillechelt** [comment]
You are raising a good question there, last time I checked, you couldn't set a few options like `'src', 'dest', 'dir'` but it has evolved over the last months. <strike>As soon as grunt 0.4.0 is out and grunt-contrib-compass can be used in production I will evaluate this question again</strike>.

**Comment by khalillechelt** [comment]
I have been talking to @sindresorhus in order to figure out if it makes sense to merge the two plugins. Since the feature set of grunt-contrib-compass has greatly improved and the grunt-contrib-\* convention is the preferred way to go for "official" grunt plugins from Grunt v0.4.0 on, we will work together to merge two plugins so that no options of grunt-compass will be missing in grunt-contrib-compass and you will be able to use it in the same way as grunt-compass when Grunt v0.4.0 drops.

Until then I will continue maintaining this plugin and as soon as it is safe to make the transition I will offer documentation on how to safely migrate from grunt-compass to grunt-contrib-compass. 

grunt-compass will work with Grunt v0.4.0 though, so your setup won't break if you only upgrade Grunt.

**Comment by khalillechelt** [comment]
Ok guys, Grunt.js 0.4.0 is out and this plugin is now deprecated. 

Please migrate over to the new Grunt  and https://github.com/gruntjs/grunt-contrib-compass asap. 
I think @sindresorhus got all the features in there. I went through it with him. If not, please don't hesitate to open an issue or better: send a PR.

Please let me know if a migration guide is needed! It looks all very straight forward to me so I am not sure if there is any need for it. 

Cheers!

– Kahlil

**Comment by ghost** [comment]
Ha. I'm gonna close this now.

**Comment by khalillechelt** [comment]
Ha. Good call.
