### ISSUE TITLE
Needs to process paths

### ISSUE THREAD

**Issue by necolas** [khalillechelt/grunt-compass#9]
At the moment, you cannot use `<% template %>` style templates in the config paths.
You need to do something like this:

``` js
src = grunt.template.process(this.data.src),
dest = grunt.template.process(this.data.dest),
```

**Comment by khalillechelt** [comment]
Ah. Good point. I will look into it as soon as I can.

**Comment by khalillechelt** [comment]
Can you give me an example so I can test an reproduce? 

Also, I want to make sure: do you by any chance mean using `<config:compass.dev.src>` like in this setup? 

``` js
compass: {
    dev: {
        src: 'assets/scss',
        dest: 'assets/css',
        linecomments: true,
        images: 'assets/images'
    },
    prod: {
        src: '<config:compass.dev.src>',
        dest: '<config:compass.dev.dest>',
        outputstyle: 'compressed',
        linecomments: false,
        forcecompile: true,
        images: '<config:compass.dev.images>'
    }
}
```

Because that works already.

**Comment by necolas** [comment]
This type: `src: "<%= basepath %>/sass"`

**Comment by khalillechelt** [comment]
Ok I added the processing call like you suggested above. Please see if it works in your use case.

**Comment by ghost** [comment]
I think this issue caused an error with my current grunt config. Maybe I'm too stupid but the grunt-config (excerpt below) won't work anymore - I get an `<WARN> An error occurred while processing a template (Cannot call method 'indexOf' of undefined). Use --force to continue. </WARN>` - I think it is because I did not specify the src/dest-variables:

```
...

    compass: {
      dev: {
        outputstyle: 'expanded',
        linecomments: true
      },
      deploy: {
        outputstyle: 'compressed',
        linecomments: false,
        forcecompile: true
      }
    },

...

    watch: {
      files: ['<config:lint.files>', 'scss/*.scss'],
      tasks: 'default'
    },  

...

grunt.registerTask('default', 'compass:dev lint concat macreload');
grunt.registerTask('deploy', 'compass:deploy lint concat min pngmin jpgmin'); 
```

I still have a config.rb file inside the folder, where I specify additional stuff such as `add_import_path` and `fonts_dir` - do I now have to specify src/dest in the grunt.js as well to get this working again?

Other idea: also include the fonts_dir and add_import_path (if possible) so I can get rid of the config.rb-file ;-)
